# Generated by Django 6.0.3 on 2026-04-07 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'ordering': ('sort',), 'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
    ]
