# Generated by Django 6.0.3 on 2026-04-07 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Сервис', 'verbose_name_plural': 'Сервисы'},
        ),
    ]
