# Generated by Django 6.0.3 on 2026-04-07 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeinfo',
            options={'verbose_name': 'Информация о нас', 'verbose_name_plural': 'Информация о нас'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
