# Generated by Django 6.0.3 on 2026-04-07 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_category_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('sort',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ('sort',), 'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
    ]
